// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2ibXAgt4nXX5z9hC5VD8jst52XoDEZo',
    appId: '1:498512468096:android:c278c26dc2554a4666ee65',
    messagingSenderId: '498512468096',
    projectId: 'motomuse-2b33f',
    storageBucket: 'motomuse-2b33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJT0xf5XIXDlkzpxbZDIjPdCQEWIjOSPs',
    appId: '1:498512468096:ios:f0b66682cac7cbd366ee65',
    messagingSenderId: '498512468096',
    projectId: 'motomuse-2b33f',
    storageBucket: 'motomuse-2b33f.firebasestorage.app',
    androidClientId: '498512468096-ahrrqajq1cu13c139aqcjf60gi97e6d3.apps.googleusercontent.com',
    iosClientId: '498512468096-0r91v1hges0qnth7cc1i50a2s4jcthl0.apps.googleusercontent.com',
    iosBundleId: 'com.kallispera.motomuse',
  );
}
