"""Seed script for Netherlands riding content.

Populates Firestore with curated riding locations, biker-friendly restaurants,
and hotels for motorcycle riders in the Netherlands.

The script uses Claude Sonnet to generate compelling descriptions and Google
Street View Static API for scenic road photos.

Usage:
    # Set environment variables
    export ANTHROPIC_API_KEY=sk-ant-...
    export GOOGLE_MAPS_API_KEY=AIza...

    # Provide Firebase credentials (one of):
    #   a) GOOGLE_APPLICATION_CREDENTIALS=/path/to/service-account.json
    #   b) Place service account key at backend/firebase-sa-key.json

    python seed_data.py

    # Optional: clear existing data first
    python seed_data.py --clear
"""

import argparse
import json
import logging
import os
import sys

import anthropic
import firebase_admin
from firebase_admin import credentials, firestore
import googlemaps

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

CLAUDE_MODEL = "claude-sonnet-4-6"
STREET_VIEW_SIZE = "600x400"
STREET_VIEW_FOV = 90
STREET_VIEW_PITCH = 5
COUNTRY = "nl"

# ---------------------------------------------------------------------------
# Netherlands riding regions — curated seed data
#
# Each region has known-good coordinates for scenic roads, a center point,
# and approximate bounds.  Descriptions are generated by Claude.
# ---------------------------------------------------------------------------

REGIONS = [
    {
        "name": "South Limburg",
        "center": {"lat": 50.84, "lng": 5.87},
        "bounds_ne": {"lat": 50.92, "lng": 6.08},
        "bounds_sw": {"lat": 50.73, "lng": 5.70},
        "tags": ["twisty", "hills", "scenic", "valleys"],
        "scenery_type": "mountains",
        "scenic_roads": [
            {"lat": 50.8265, "lng": 5.9590, "heading": 180},  # Vijlenerbos
            {"lat": 50.8590, "lng": 5.8230, "heading": 90},   # Cauberg area
            {"lat": 50.7800, "lng": 5.9200, "heading": 270},  # Drielandenpunt area
        ],
    },
    {
        "name": "Veluwe",
        "center": {"lat": 52.25, "lng": 5.85},
        "bounds_ne": {"lat": 52.45, "lng": 6.10},
        "bounds_sw": {"lat": 52.05, "lng": 5.60},
        "tags": ["forests", "heathland", "sweeping", "nature"],
        "scenery_type": "forests",
        "scenic_roads": [
            {"lat": 52.0870, "lng": 5.9620, "heading": 45},   # Posbank
            {"lat": 52.3200, "lng": 5.7800, "heading": 120},  # Central Veluwe
            {"lat": 52.2400, "lng": 5.9800, "heading": 200},  # Loenen area
        ],
    },
    {
        "name": "Zeeland Coast",
        "center": {"lat": 51.50, "lng": 3.80},
        "bounds_ne": {"lat": 51.75, "lng": 4.20},
        "bounds_sw": {"lat": 51.30, "lng": 3.40},
        "tags": ["coastal", "dykes", "flat", "wind", "bridges"],
        "scenery_type": "coastline",
        "scenic_roads": [
            {"lat": 51.6510, "lng": 3.6850, "heading": 270},  # Brouwersdam
            {"lat": 51.5300, "lng": 3.5500, "heading": 180},  # Westkapelle dyke
            {"lat": 51.4400, "lng": 4.0200, "heading": 90},   # Oosterscheldekering
        ],
    },
    {
        "name": "Drenthe",
        "center": {"lat": 52.90, "lng": 6.60},
        "bounds_ne": {"lat": 53.10, "lng": 6.90},
        "bounds_sw": {"lat": 52.70, "lng": 6.30},
        "tags": ["quiet", "forests", "heathland", "historic"],
        "scenery_type": "forests",
        "scenic_roads": [
            {"lat": 52.9400, "lng": 6.5800, "heading": 90},   # Dwingeloo area
            {"lat": 52.8500, "lng": 6.7200, "heading": 180},  # Hondsrug
            {"lat": 52.8800, "lng": 6.4500, "heading": 45},   # Dwingelderveld
        ],
    },
    {
        "name": "Achterhoek",
        "center": {"lat": 52.00, "lng": 6.45},
        "bounds_ne": {"lat": 52.15, "lng": 6.75},
        "bounds_sw": {"lat": 51.85, "lng": 6.15},
        "tags": ["rolling", "quiet", "countryside", "backroads"],
        "scenery_type": "mixed",
        "scenic_roads": [
            {"lat": 52.0400, "lng": 6.3200, "heading": 135},  # Zutphen area
            {"lat": 51.9700, "lng": 6.5100, "heading": 270},  # Winterswijk area
            {"lat": 52.0100, "lng": 6.6800, "heading": 90},   # Near German border
        ],
    },
    {
        "name": "Utrechtse Heuvelrug",
        "center": {"lat": 52.08, "lng": 5.35},
        "bounds_ne": {"lat": 52.18, "lng": 5.55},
        "bounds_sw": {"lat": 51.98, "lng": 5.15},
        "tags": ["wooded", "hills", "estates", "scenic"],
        "scenery_type": "forests",
        "scenic_roads": [
            {"lat": 52.0500, "lng": 5.2800, "heading": 45},   # Amerongen
            {"lat": 52.1200, "lng": 5.3500, "heading": 180},  # Doorn area
            {"lat": 52.0800, "lng": 5.4200, "heading": 270},  # Driebergen
        ],
    },
    {
        "name": "Overijssel Salland",
        "center": {"lat": 52.45, "lng": 6.30},
        "bounds_ne": {"lat": 52.60, "lng": 6.55},
        "bounds_sw": {"lat": 52.30, "lng": 6.05},
        "tags": ["rolling", "rivers", "farmland", "quiet"],
        "scenery_type": "mixed",
        "scenic_roads": [
            {"lat": 52.4300, "lng": 6.2500, "heading": 90},   # Sallandse Heuvelrug
            {"lat": 52.5100, "lng": 6.3800, "heading": 180},  # Ommen area
            {"lat": 52.3800, "lng": 6.1500, "heading": 45},   # Deventer area
        ],
    },
    {
        "name": "Noord-Brabant Kempen",
        "center": {"lat": 51.45, "lng": 5.30},
        "bounds_ne": {"lat": 51.60, "lng": 5.60},
        "bounds_sw": {"lat": 51.30, "lng": 5.00},
        "tags": ["forests", "heathland", "quiet", "sandy"],
        "scenery_type": "forests",
        "scenic_roads": [
            {"lat": 51.5800, "lng": 5.2300, "heading": 180},  # Oisterwijk forests
            {"lat": 51.4200, "lng": 5.3800, "heading": 90},   # Kempen area
            {"lat": 51.4900, "lng": 5.1500, "heading": 270},  # Loonse Duinen
        ],
    },
]


# ---------------------------------------------------------------------------
# Claude description generation
# ---------------------------------------------------------------------------


def _generate_descriptions(client: anthropic.Anthropic) -> dict:
    """Use Claude to generate descriptions for all regions, restaurants, and hotels."""

    region_names = [r["name"] for r in REGIONS]
    region_list = "\n".join(f"- {name}" for name in region_names)

    prompt = f"""You are an expert on motorcycle touring in the Netherlands. Generate curated content for a motorcycle navigation app.

For each of these riding regions, provide:
1. A compelling 2-3 sentence description of why this area is great for motorcyclists (road character, scenery, what makes it special)
2. Two well-known, real restaurants in or near the region that would be great stops for motorcycle breakfast/lunch runs. These MUST be real, existing establishments.
3. One well-known, real hotel or B&B in or near the region suitable for an overnight motorcycle trip. This MUST be a real, existing establishment.

Regions:
{region_list}

For each restaurant include: name, a 1-2 sentence description of why bikers would love it, approximate latitude/longitude, cuisine type, and price range (€, €€, or €€€).

For each hotel include: name, a 1-2 sentence description, approximate latitude/longitude, price range, and biker-friendly amenities (e.g., secure parking, drying room, garage).

Respond in this exact JSON format:
{{
  "regions": [
    {{
      "name": "Region Name",
      "description": "Why this area is amazing for motorcyclists...",
      "restaurants": [
        {{
          "name": "Restaurant Name",
          "description": "Why bikers love this place...",
          "lat": 50.85,
          "lng": 5.90,
          "cuisine_type": "Dutch",
          "price_range": "€€"
        }}
      ],
      "hotels": [
        {{
          "name": "Hotel Name",
          "description": "Why this is great for an overnight bike trip...",
          "lat": 50.84,
          "lng": 5.88,
          "price_range": "€€",
          "biker_amenities": ["secure parking", "drying room"]
        }}
      ]
    }}
  ]
}}

Important: Only include REAL establishments that actually exist. Use accurate coordinates."""

    logger.info("Generating descriptions with Claude Sonnet...")
    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )

    # Extract JSON from response
    text = response.content[0].text
    # Find JSON block (may be wrapped in ```json ... ```)
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    return json.loads(text)


# ---------------------------------------------------------------------------
# Google Street View photo URLs
# ---------------------------------------------------------------------------


def _street_view_url(lat: float, lng: float, heading: int, api_key: str) -> str:
    """Build a Google Street View Static API URL."""
    return (
        f"https://maps.googleapis.com/maps/api/streetview"
        f"?size={STREET_VIEW_SIZE}"
        f"&location={lat},{lng}"
        f"&heading={heading}"
        f"&fov={STREET_VIEW_FOV}"
        f"&pitch={STREET_VIEW_PITCH}"
        f"&key={api_key}"
    )


def _check_street_view_coverage(
    lat: float, lng: float, api_key: str,
) -> bool:
    """Check if Street View coverage exists at the given coordinates."""
    url = (
        f"https://maps.googleapis.com/maps/api/streetview/metadata"
        f"?location={lat},{lng}"
        f"&key={api_key}"
    )
    import requests as req

    resp = req.get(url, timeout=10)
    if resp.status_code == 200:
        data = resp.json()
        return data.get("status") == "OK"
    return False


def _generate_photo_urls(region: dict, api_key: str) -> list[str]:
    """Generate Street View photo URLs for a region's scenic roads."""
    urls = []
    for road in region.get("scenic_roads", []):
        if _check_street_view_coverage(road["lat"], road["lng"], api_key):
            urls.append(
                _street_view_url(road["lat"], road["lng"], road["heading"], api_key)
            )
    return urls


# ---------------------------------------------------------------------------
# Firestore write operations
# ---------------------------------------------------------------------------


def _clear_collections(db: firestore.firestore.Client) -> None:
    """Delete all documents in the riding content collections."""
    for collection in ("riding_locations", "restaurants", "hotels"):
        logger.info("Clearing %s...", collection)
        docs = db.collection(collection).stream()
        for doc in docs:
            doc.reference.delete()


def _write_to_firestore(
    db: firestore.firestore.Client,
    descriptions: dict,
    api_key: str,
) -> None:
    """Write all curated data to Firestore."""
    regions_data = descriptions.get("regions", [])

    for order, region_seed in enumerate(REGIONS):
        # Match Claude's description data to our seed region
        region_desc = next(
            (r for r in regions_data if r["name"] == region_seed["name"]),
            None,
        )
        if not region_desc:
            logger.warning("No description found for %s, skipping", region_seed["name"])
            continue

        # Generate Street View photos
        photo_urls = _generate_photo_urls(region_seed, api_key)
        logger.info(
            "  %s: %d Street View photos", region_seed["name"], len(photo_urls),
        )

        # Write riding location
        location_ref = db.collection("riding_locations").document()
        location_id = location_ref.id
        location_data = {
            "country": COUNTRY,
            "name": region_seed["name"],
            "description": region_desc["description"],
            "center": firestore.firestore.GeoPoint(
                region_seed["center"]["lat"], region_seed["center"]["lng"],
            ),
            "bounds_ne": firestore.firestore.GeoPoint(
                region_seed["bounds_ne"]["lat"], region_seed["bounds_ne"]["lng"],
            ),
            "bounds_sw": firestore.firestore.GeoPoint(
                region_seed["bounds_sw"]["lat"], region_seed["bounds_sw"]["lng"],
            ),
            "photo_urls": photo_urls,
            "tags": region_seed["tags"],
            "scenery_type": region_seed["scenery_type"],
            "order": order,
        }
        location_ref.set(location_data)
        logger.info("  Wrote location: %s", region_seed["name"])

        # Write restaurants
        for r_order, restaurant in enumerate(region_desc.get("restaurants", [])):
            rest_ref = db.collection("restaurants").document()
            rest_data = {
                "country": COUNTRY,
                "name": restaurant["name"],
                "description": restaurant["description"],
                "location": firestore.firestore.GeoPoint(
                    restaurant["lat"], restaurant["lng"],
                ),
                "riding_location_id": location_id,
                "riding_location_name": region_seed["name"],
                "photo_urls": [],  # Restaurants don't get Street View by default
                "cuisine_type": restaurant.get("cuisine_type", "Mixed"),
                "price_range": restaurant.get("price_range", "€€"),
                "google_place_id": "",
                "order": order * 10 + r_order,
            }
            rest_ref.set(rest_data)
            logger.info("    Wrote restaurant: %s", restaurant["name"])

        # Write hotels
        for h_order, hotel in enumerate(region_desc.get("hotels", [])):
            hotel_ref = db.collection("hotels").document()
            hotel_data = {
                "country": COUNTRY,
                "name": hotel["name"],
                "description": hotel["description"],
                "location": firestore.firestore.GeoPoint(
                    hotel["lat"], hotel["lng"],
                ),
                "riding_location_id": location_id,
                "riding_location_name": region_seed["name"],
                "photo_urls": [],
                "price_range": hotel.get("price_range", "€€"),
                "biker_amenities": hotel.get("biker_amenities", []),
                "google_place_id": "",
                "order": order * 10 + h_order,
            }
            hotel_ref.set(hotel_data)
            logger.info("    Wrote hotel: %s", hotel["name"])


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed Netherlands riding content")
    parser.add_argument(
        "--clear", action="store_true", help="Clear existing data before seeding",
    )
    args = parser.parse_args()

    # Validate environment
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    maps_key = os.environ.get("GOOGLE_MAPS_API_KEY")
    if not anthropic_key:
        logger.error("ANTHROPIC_API_KEY not set")
        sys.exit(1)
    if not maps_key:
        logger.error("GOOGLE_MAPS_API_KEY not set")
        sys.exit(1)

    # Initialise Firebase Admin
    sa_path = os.environ.get(
        "GOOGLE_APPLICATION_CREDENTIALS",
        os.path.join(os.path.dirname(__file__), "firebase-sa-key.json"),
    )
    if os.path.exists(sa_path):
        cred = credentials.Certificate(sa_path)
        firebase_admin.initialize_app(cred)
        logger.info("Firebase initialised with service account: %s", sa_path)
    else:
        # Try Application Default Credentials (e.g. on GCP)
        firebase_admin.initialize_app()
        logger.info("Firebase initialised with Application Default Credentials")

    db = firestore.client()

    if args.clear:
        _clear_collections(db)
        logger.info("Cleared existing data.")

    # Generate descriptions with Claude
    claude = anthropic.Anthropic(api_key=anthropic_key)
    descriptions = _generate_descriptions(claude)

    # Write to Firestore
    logger.info("Writing to Firestore...")
    _write_to_firestore(db, descriptions, maps_key)

    # Summary
    logger.info("Seed complete!")
    logger.info(
        "  %d riding locations, ~%d restaurants, ~%d hotels",
        len(REGIONS),
        len(REGIONS) * 2,
        len(REGIONS),
    )


if __name__ == "__main__":
    main()
